name: pomo
description: "Your Pomodoro Buddy."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  pine: ^1.0.3
  retrofit: ^4.1.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  permission_handler: ^12.0.0+1
  auto_route: ^10.1.0+1
  auto_route_generator: ^10.1.0
  flutter_native_splash: ^2.3.10
  dotted_border: ^2.1.0
  bloc: ^9.0.0
  flutter_secure_storage: ^10.0.0-beta.2
  path_provider: ^2.1.4
  hydrated_bloc: ^10.0.0
  hive: ^2.2.3
  email_validator: ^3.0.0
  dio: ^5.4.1
  image_picker: ^1.0.7
  confetti: ^0.8.0
  numberpicker: ^2.1.2
  skeletonizer: ^1.4.2
  flutter_slidable: ^4.0.0
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.2.1
  flutter_cache_manager: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_otp_text_field: ^1.1.3+2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path: ^1.9.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  flutter_localization: ^0.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  audioplayers: ^6.1.0
  table_calendar: ^3.1.2
  pinput: ^5.0.0
  url_launcher: ^6.3.0
  android_intent_plus: ^5.1.0
  timezone: ^0.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  data_fixture_dart: ^3.0.0
  freezed: ^3.0.0-0.0.dev
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  retrofit_generator: ^9.1.2


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/icons/nav-bar/Bold/
    - assets/icons/nav-bar/Light/

